### ISSUE TITLE
autoHeadersMiddleware throws error

### ISSUE THREAD

**Issue by sh** [snd/fragments#1]
refactored to fragments_MIDDLEWARE got: 

```
ERROR
[Error: needs one argument which must be an object]
Error: needs one argument which must be an object
  at /project/node_modules/fragments/lib/request/header.js:53:13
  at /project/node_modules/fragments/lib/application/auto-headers.js:17:5
  at process._tickDomainCallback (node.js:486:13)
```

**Comment by snd** [comment]
fixed and added to tests in 0.1.4
